pipeline:
  name: 17 oct test bi
  identifier: _oct_test_bi
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fd
                  identifier: fd
                  type: HarnessApproval
                  timeout: <+input>
                  spec:
                    approvalMessage: |-
                      Please review the following info
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
