pipeline:
  name: accountTemplateRemotePMS
  identifier: accountTemplateRemotePMS
  projectIdentifier: templateGitXDemo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: account.accountStageRemote
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adasfsf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
