pipeline:
  name: adsfasd123
  identifier: adsfasd123
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsaf
        identifier: dsaf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sda
                  identifier: sda
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.testUserGroup2
                    approverInputs: []
        tags: {}
