pipeline:
  name: adsfadf
  identifier: adsfadf
  projectIdentifier: gitX_demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdfas
        identifier: asdfas
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdafasd
                  identifier: sdafasd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
