pipeline:
  name: asdfasdfsadfadsfsaf
  identifier: asdfasdfsadfadsfsaf
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdfasdf
        identifier: asdfasdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdfasdfasfda
                  identifier: sdfasdfasfda
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
