pipeline:
  name: asdfasdfasdfas
  identifier: asdfasdfasdfas
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sadf
        identifier: sadf
        template:
          templateRef: test_inline_template1231231231231
          versionLabel: vsd
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adsf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
