pipeline:
  name: asdfas
  identifier: asdfas
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: adsf
        identifier: adsf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: adf
                  identifier: adf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
