pipeline:
  name: bbPipeline2
  identifier: bbPipeline2
  projectIdentifier: Git_Caching
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stageBugBashTemplate
          versionLabel: v1
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: bbStage2
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: EW
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: bbStage3
          versionLabel: v1
    - stage:
        name: s4
        identifier: s4
        template:
          templateRef: bbStage4
          versionLabel: v1
    - stage:
        name: s5
        identifier: s5
        template:
          templateRef: bbStage5
          versionLabel: v
    - stage:
        name: s6
        identifier: s6
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ss1
                  identifier: ss1
                  template:
                    templateRef: bbStep1
                    versionLabel: v
              - step:
                  name: ss2
                  identifier: ss2
                  template:
                    templateRef: bbStep2
                    versionLabel: v
              - step:
                  name: ss3
                  identifier: ss3
                  template:
                    templateRef: bbStep3
                    versionLabel: v
        tags: {}
