pipeline:
  name: case1Dec19
  identifier: case1Dec19
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: a1
        identifier: a1
        template:
          templateRef: stageMainDec19
          versionLabel: v1
