pipeline:
  name: CI Elastic
  identifier: CI_Elastic
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: CIplay
              namespace: test
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: CV_Docker
                    image: test
                    shell: Sh
                    command: echo S1
