pipeline:
  name: dec5Pipeline
  identifier: dec5Pipeline
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: Nov18Stage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
