pipeline:
  name: demoPipelineSept08Account
  identifier: demoPipelineSept08Account
  projectIdentifier: demo_gitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: account.sept7accountStage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: account_approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
