pipeline:
  name: dsfdsf
  identifier: dsfdsf
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fcb
        identifier: fcb
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: dsfvasd
                  identifier: dsfvasd
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
