pipeline:
  name: f8_p1
  identifier: f8_p1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: f8_stage2_r1_m
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asd
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
