pipeline:
  name: jan3Inline8
  identifier: jan3Inline8
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsa
        identifier: dsa
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsa
                  identifier: dsa
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
