pipeline:
  name: mainAndNonDefaultPms
  identifier: mainAndNonDefaultPms
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdf
        identifier: asdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsaf - new branch
                  identifier: dsaf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
