pipeline:
  name: nonDefaultP3
  identifier: nonDefaultP3
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: lkm
        identifier: lkm
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: jh
                  identifier: jh
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
