pipeline:
  name: Nov18P1
  identifier: Nov18P1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ss
        identifier: ss
        template:
          templateRef: Nov18Stage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
