pipeline:
  name: p2
  identifier: p2
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdfa
        identifier: asdfa
        template:
          templateRef: PipelineUseStageRemote
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: r1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
