pipeline:
  name: p2NestedPatch14
  identifier: p2NestedPatch14
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: nestedStage14PatchR1
          versionLabel: v1
