pipeline:
  name: p4
  identifier: p4
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stageT1
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
