pipeline:
  name: p5
  identifier: p5
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: stages1T2
          versionLabel: v2
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
