pipeline:
  name: parent pipeline rmeote
  identifier: parent_pipeline_rmeote
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: chained
        identifier: chained
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: child_pipeline_remote1
          project: naidusanity
          outputs: []
