pipeline:
  name: pipeline testRepo
  identifier: pipeline_testRepo
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdf
        identifier: asdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dfs
                  identifier: dfs
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following info
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
