pipeline:
  name: pipelineUiTest
  identifier: pipelineUiTest
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cv
        identifier: cv
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdf
                  identifier: sdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progressionfvdvdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.testUserGroup2
                    approverInputs: []
        tags: {}
