pipeline:
  name: pipelineBugBash
  identifier: pipelineBugBash
  projectIdentifier: Git_Caching
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stageBugBashTemplate
          versionLabel: v1
