pipeline:
  name: pipelineq1
  identifier: pipelineq1
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: stage1
          versionLabel: q1
