pipeline:
  name: pms2Feb2
  identifier: pms2Feb2
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stage2Feb2
          versionLabel: c1
