pipeline:
  name: prodTestPipelineAccountTEmpalte
  identifier: prodTestPipelineAccountTEmpalte
  projectIdentifier: testNewGitExp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dfg
        identifier: dfg
        template:
          templateRef: account.stageSept22
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adfva
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
