template:
  name: prodTestOldGitSycn
  identifier: prodTestOldGitSycn
  type: Step
  projectIdentifier: testOldGitSync
  orgIdentifier: default
  tags: {}
  spec:
    timeout: 10m
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo "hiiii"
      environmentVariables: []
      outputVariables: []
      executionTarget: {}
  versionLabel: v2
