pipeline:
  name: reference Dec1222
  identifier: reference_Dec1222
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: w
        identifier: w
        template:
          templateRef: Nov18Stage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
