pipeline:
  name: remoteTemplateAndRemotePipeline
  identifier: remoteTemplateAndRemotePipeline
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        template:
          templateRef: asd
          versionLabel: fsd
