pipeline:
  name: remotePipelineRemoteTemplateP2
  identifier: remotePipelineRemoteTemplateP2
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stageDec13
          versionLabel: v1
