pipeline:
  name: remoteSept29P1
  identifier: remoteSept29P1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ffg
        identifier: ffg
        template:
          templateRef: remoteStageSept29
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: dsv
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
