pipeline:
  name: remotePipelineSept29
  identifier: remotePipelineSept29
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fg
        identifier: fg
        template:
          templateRef: remoteStageSept29
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: dsv
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
