pipeline:
  name: sdfasdfsdfsdafdsf
  identifier: sdfasdfsdfsdafdsf
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: dsa
        identifier: dsa
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fasd
                  identifier: fasd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
