pipeline:
  name: sdfasdf
  identifier: sdfasdf
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: testStageR1NonDefault
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
