pipeline:
  name: sdfasdfs
  identifier: sdfasdfs
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dcasmk
        identifier: dcasml
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sadfas
                  identifier: sadfas
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.testUserGroup2
                    approverInputs: []
        tags: {}
