pipeline:
  name: sept7p1
  identifier: sept7p1
  projectIdentifier: demo_gitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s1
                  identifier: s1
                  template:
                    templateRef: sept7StepRemoteMain
                    versionLabel: v1
        tags: {}
