pipeline:
  name: sept13p1main
  identifier: sept13p1main
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: sept13StageMain
          versionLabel: v1
