pipeline:
  name: specialChar
  identifier: specialChar
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: dsf
        identifier: dsf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsfa
                  identifier: dsfa
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
