pipeline:
  name: test bi ND
  identifier: test_bi_ND
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fds
        identifier: fds
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdf
                  identifier: sdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information123456789
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
