pipeline:
  name: testRemoteTempaltePipelien1
  identifier: testRemoteTempaltePipelien1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s123
        identifier: s123
        template:
          templateRef: k8sMigration12Dec
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: manifest1
                          type: Kustomize
                          spec:
                            store:
                              type: Github
                              spec:
                                repoName: <+input>
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
