pipeline:
  name: testPipelinedev12
  identifier: testPipelinedev12
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: StageDeploy12Dec
          versionLabel: "1"
