pipeline:
  name: test repo pipwlinw123
  identifier: test_repo_pipwlinw123
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsf123
                  identifier: dsf123
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following info123456
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
