pipeline:
  name: testTriggerPipeline
  identifier: testTriggerPipeline
  projectIdentifier: test_mohit_git_sync_to_gitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script
                  identifier: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
