pipeline:
  name: test testrepo piepline
  identifier: test_testrepo_piepline
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sagd
        identifier: sagd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sd
                  identifier: sd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
                    callbackId: "1"
        tags: {}
