template:
  name: prod ND stage1
  identifier: prod_ND_stage1
  versionLabel: vsd
  type: Stage
  projectIdentifier: TestGitSync
  orgIdentifier: default
  tags: {}
  spec:
    type: Approval
    spec:
      execution:
        steps:
          - step:
              name: sdfsdf
              identifier: sdfsdf
              type: HarnessApproval
              timeout: 1d
              spec:
                approvalMessage: |-
                  Please review the following information
                  and approve the pipeline progression
                includePipelineExecutionHistory: true
                approvers:
                  minimumCount: <+input>
                  disallowPipelineExecutor: false
                  userGroups: <+input>
                isAutoRejectEnabled: false
                approverInputs: []
