pipeline:
  name: Demo pipeline
  identifier: Demo_pipeline
  projectIdentifier: demoproject
  orgIdentifier: organization1
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: s1
                  identifier: s1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information update
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: stage2
        identifier: stage2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: test
                  identifier: test
                  template:
                    templateRef: teststeptemplate
                    versionLabel: v1
        tags: {}
